//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homecare.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int id_schedule { get; set; }
        public System.DateTime schedule_start { get; set; }
        public System.DateTime schedule_end { get; set; }
        public int fk_staff_schedule { get; set; }
        public int fk_route_schedule { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
