//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homecare.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int id_staff { get; set; }
        public string staff_name { get; set; }
        public int fk_occupation_staff { get; set; }
    
        public virtual Occupation Occupation { get; set; }
    }
}
